name: chewie_audio
description: An audio player for Flutter with Cupertino and Material play controls
version: 1.1.1
homepage: https://github.com/Sub6Resources/chewie_audio
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>
  - Matthew Whitaker <sub6resources@gmail.com>
  - Eric Kok <erickok@gmail.com>

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  video_player: ^1.0.0
  cupertino_icons: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true
