name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.6.0
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.11.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  video_player: ^2.7.0
  wakelock_plus: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
