name: in_app_picture_in_picture
description: A video player for Flutter with Cupertino and Material play controls
publish_to: "none"
version: 0.0.1

environment:
   sdk: ">=2.13.0 <3.0.0"
   flutter: ">=1.22.0"

dependencies:
   cupertino_icons: ^1.0.4
   flutter:
      sdk: flutter
   provider: ^6.0.1
   video_player: ^2.2.7
   wakelock: ^0.5.6

dev_dependencies:
   flutter_test:
      sdk: flutter
   lint: ^1.8.1

flutter:
   uses-material-design: true
