name: chewie_audio
description: An audio player for Flutter with Cupertino and Material play controls
version: 1.2.0
homepage: https://github.com/Sub6Resources/chewie_audio
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>
  - Matthew Whitaker <sub6resources@gmail.com>
  - Eric Kok <erickok@gmail.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  video_player: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  uses-material-design: true
