name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.10.4
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  video_player: ">=0.10.12+5 <2.0.0"
  cupertino_icons: ">=1.0.0 <2.0.0"
  wakelock: ">=0.1.2 <1.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
