name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.0.0
homepage: https://github.com/brianegan/chewie

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  video_player: ^2.0.0
  wakelock: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
