name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.2.3
homepage: https://github.com/brianegan/chewie

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.1
  video_player: ^2.2.7
  wakelock: ^0.6.1+1
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true
