name: chewie_audio
description: An audio player for Flutter with Cupertino and Material play controls
version: 1.0.0
homepage: https://github.com/Sub6Resources/chewie_audio
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>
  - Matthew Whitaker <sub6resources@gmail.com>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player: ">=0.7.0 <0.11.0"
  screen: ">=0.0.4 <0.1.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
